### ISSUE TITLE
About Unitopatho Dataset

### ISSUE THREAD

**Issue by sky1652169058** [Jiawei-Yang/ReMix#1]
Hi YANG！
After you shared your Unitopatho dataset ,i tried train remix with it.
But i found that when i use prototypes, the result is strange, the trained model seems to classify randomly
just like：
`
INFO Precision, Recall, Accuracy, Avg
INFO 11.13 24.25 13.64 16.34
`
So i tried train it without prototypes so that i can output feature name and its label, and i found they can't match
and the result is：
`
INFO Precision, Recall, Accuracy, Avg
INFO 9.89 19.47 14.77 14.71
`

So i think may the train_bag_feats_proto_1.npy and train_bag_labels.npy you shared can't match？

Or is there another reason for this problem?

Looking forward to your kind help！

**Comment by Jiawei-Yang** [comment]
Hi, the results are pretty weird. Unfortunately, I've been very busy recently. I might have time to check them next week. Stay tuned.

**Comment by Jiawei-Yang** [comment]
Hi,

I can reproduce the results.

Please check [here](https://github.com/Jiawei-Yang/ReMix/issues/2#issuecomment-1288229407) for a follow-up.

**Comment by sky1652169058** [comment]
Thanks for your kind help！
