### ISSUE TITLE
Reproduce results

### ISSUE THREAD

**Issue by HHHedo** [Jiawei-Yang/ReMix#3]
Hi Jiawei,
Thank you for your help again!
As you mentioned in #2, the results can be achieved by `np.sort`, but I don't know why it works. As the labels are encoded in the name of each feature file, e.g., the label of **TA.LG CASO 107_3.npy** should be **3**, there should be no problem with features and labels. As the train and test are saved in different files, there should be no problem with data leaking problem either. 
Could you please explain more about `np.sort`?
Thank you for your patient help.

Best,
Tiancheng

**Comment by HHHedo** [comment]
I wonder whether we are using the same features. In your code, the baseline uses the features of
https://github.com/Jiawei-Yang/ReMix/blob/3b6a518081793fd8dc7fcace297f7b208ab11d3a/train_remix.py#L296.
Is that the same with [ReMix](https://github.com/Jiawei-Yang/ReMix)/[datasets](https://github.com/Jiawei-Yang/ReMix/tree/master/datasets)/[Unitopatho](https://github.com/Jiawei-Yang/ReMix/tree/master/datasets/Unitopatho)/[meta](https://github.com/Jiawei-Yang/ReMix/tree/master/datasets/Unitopatho/meta)/train_list.txt

**Comment by Jiawei-Yang** [comment]
> Hi Jiawei, Thank you for your help again! As you mentioned in #2, the results can be achieved by `np.sort`, but I don't know why it works. As the labels are encoded in the name of each feature file, e.g., the label of **TA.LG CASO 107_3.npy** should be **3**, there should be no problem with features and labels. As the train and test are saved in different files, there should be no problem with data leaking problem either. Could you please explain more about `np.sort`? Thank you for your patient help.
> 
> Best, Tiancheng

Hi tiancheng,

I don't know if you have changed my implementation. However, in my current repo, I didn't read labels from file names. Instead, I load training & testing labels from pre-stored `npz` files (see [here](https://github.com/Jiawei-Yang/ReMix/blob/3b6a518081793fd8dc7fcace297f7b208ab11d3a/train_remix.py#L251)). That's actually my bad in the implementation part. When training on full-bags (baseline), I load training/testing features via `train_list.txt` (see [here](https://github.com/Jiawei-Yang/ReMix/blob/3b6a518081793fd8dc7fcace297f7b208ab11d3a/train_remix.py#L296)) and assume the order of bags is the same as `train_bag_labels .npy`.

So, if the file names in `train_list.txt` were not sorted, they don't match the order in `train_bag_labels.npy`.

**Comment by Jiawei-Yang** [comment]
> I wonder whether we are using the same features. In your code, the baseline uses the features of
> 
> https://github.com/Jiawei-Yang/ReMix/blob/3b6a518081793fd8dc7fcace297f7b208ab11d3a/train_remix.py#L296
> 
> .
> Is that the same with [ReMix](https://github.com/Jiawei-Yang/ReMix)/[datasets](https://github.com/Jiawei-Yang/ReMix/tree/master/datasets)/[Unitopatho](https://github.com/Jiawei-Yang/ReMix/tree/master/datasets/Unitopatho)/[meta](https://github.com/Jiawei-Yang/ReMix/tree/master/datasets/Unitopatho/meta)/train_list.txt

Yes, they are the same.

**Comment by HHHedo** [comment]
> 

My code is based on dsmil, and I rewrite the dataset of Unitopatho. The features are from` Unitopatho_feats/train_npy` and the labels are decoded from the last number(`feat_name.split('_')[1].split('.')[0]`). So, in my implementation, there should be no problem with order mismatch.

**Comment by Jiawei-Yang** [comment]
Hi tiancheng,

It might be other implementation mismatches between this repo and your own implementation. The reproduced results I showed in the previous issue are obtained by just cloning this repo and plugging in the Unitopatho features this afternoon in a different machine.

Based on current information, I have no idea why the results didn't match in your own implementation, and it is slightly out of the scope of this repo. 

I'm still in a busy month, so I might not be able to reply in time. Kindly consider using this repo to see if you can get the matched results and then debug.

Best,
Jiawei

**Comment by HHHedo** [comment]
Thank you! I will try this repo to reproduce.One more question about the evaluation: Should the further research follow the proposed one? Could you provide more results like the evaluation in dsmil?Thank you for your quick help again!在 2022年10月24日，11:56，Eadien ***@***.***> 写道：﻿
Hi tiancheng,
It might be other implementation mismatches between this repo and your own implementation. The reproduced results I showed in the previous issue are obtained by just cloning this repo and plugging in the Unitopatho features this afternoon in a different machine.
Based on current information, I have no idea why the results didn't match in your own implementation, and it is slightly out of the scope of this repo.
I'm still in a busy month, so I might not be able to reply in time. Kindly consider using this repo to see if you can get the matched results and then debug.
Best,
Jiawei

**Comment by Jiawei-Yang** [comment]
I'm not sure what your question is. Can you clarify it?

**Comment by HHHedo** [comment]
Using argmax for binary predictions.在 2022年10月24日，12:11，Eadien ***@***.***> 写道：﻿
I'm not sure what your question is. Can you clarify it?

**Comment by Jiawei-Yang** [comment]
Our current evaluation protocol mainly follows DSMIL. I might add your suggestion to future plans. 
You're welcome to explore by yourself.
