### ISSUE TITLE
environment settings

### ISSUE THREAD

**Issue by jjjharden** [Jiawei-Yang/ReMix#4]
Hi, thank you for your sharing!

I met some problems when I tried to reproduce your work,which was seemly caused by some package version:

> LinAlgError: SVD did not converge

Can you tell me your faiss and some other packages' version? Thank you very much!

**Comment by Jiawei-Yang** [comment]
Hi there,

It is in fact not an environment issue. This problem would occur in those bags with a low amount of patches, where the covariance matrix would be ill-defined for multi-variate sampling. For example, sometimes a cluster can have only one sample or even zero samples. 

I don't remember what exact steps I'd taken. But, I think I have tried the following to overcome the issue:
1) Change the random seed of faiss clustering for that particular case.
2) Simply repeat the features of that bag multiple times. This will increase the minimal size of resulted clusters. However, the covariance matrix can still be problematic in this way (as repeated samples within a cluster have no variance).
3) Just return a diagonal matrix with a small scalar variance, for example, `epsilon * np.eye(512)`, where epsilon can be empirically set per other cases.
